[package]
name = "phab"
version = "0.2.0"
authors = ["Sendy Halim <sendyhalim93@gmail.com>"]
edition = "2018"
description = """\
  CLI utility client for phabricator (https://www.phacility.com/phabricator)
"""
readme = "../readme.md"
homepage = "https://github.com/sendyhalim/phab"
repository = "https://github.com/sendyhalim/phab"
keywords = ["cli", "phabricator", "developer-tools"]
categories = ["command-line-utilities"]
license-file = "../license"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
reqwest = { version = "0.10.4", features = ["json", "rustls-tls", "native-tls"] }
tokio = { version = "0.2", features = ["full"] }
clap = { version = "2.33" }
futures = { version = "0.3" }
failure = { version = "0.1.7" }
env_logger = { version = "0.7.1" }
log = { version = "0.4.8" }
fake = { version = "2.2", features = ["derive", "chrono"] }
rand = { version = "0.7" }
slugify = { version = "0.1.0" }

[build-dependencies]
built = "0.4"

[lib]
name = "lib"
path = "src/lib/lib.rs"

[[bin]]
name = "phab"
path = "src/bin/phab.rs"
